# 1. 네이버 뉴스 Crawling with Naver Open API

In [1]:
# 네이버 검색 API 예제 -  블로그 검색 예제를 뉴스 검색 예제로 수정하여 실행
# 네이버 검색 API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = "Dy8QoalA82Rsb0srGFyN"
client_secret = "iP03VyF_LJ"
encText = urllib.parse.quote("인공지능")
url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

{
	"lastBuildDate":"Tue, 07 Apr 2026 14:48:20 +0900",
	"total":3881571,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"컴퓨터학원 실용적인 <b>인공지능<\/b> 수업과정",
			"link":"https:\/\/blog.naver.com\/foryou1035\/224160610941",
			"description":"요즘 <b>인공지능<\/b>이 화두인데요. 처음에는 똑똑한 기능에 신기함이 컸지만, 시간이 갈수록 미묘한 감정이... 현재는 직장에서 <b>인공지능<\/b> 교육을 담당하게 되었고, 퇴근 후에는 취미로 웹사이트를 만들고 있어요.... ",
			"bloggername":"Ssong Story ♡",
			"bloggerlink":"blog.naver.com\/foryou1035",
			"postdate":"20260126"
		},
		{
			"title":"<b>인공지능<\/b> 자격증 취득과정 및 취업 정보 정리",
			"link":"https:\/\/blog.naver.com\/gustlr00\/224087574160",
			"description":"<b>인공지능<\/b> 자격증 취득과정 및 취업 정보 정리 “AI를 이해하는 사람과 그렇지 못한 사람의 차이가 점점 더 커지고 있다&quot;라는 말을 실감하게 되는 요즘, 직장 내에서도, 취업 시장에서도 <b>인공지능<\/b> 기술을 다룰... ",
			"bloggername":"〃다시 만나는 그날 까지 〃",
			"bloggerlink":"blog.naver.com\/gustlr00",
			"postdate":"20251125"
		},
		{
			"title":"<b>인공지능<\/b>전문가 자격증 취득과정 정리",
			"link":"https:\/\/blog.naver.com\/anycall2502\/224076021636",
			"description":"<b>인공지능<\/b>전문가 자격증 취득과정 정리 최근 <b>인공지능<\/b> 기술이 눈에 띄게 발전하고 있다는 걸 느끼면서 뒤처지면 안 되겠다는 생각이 들었어요. 주변에서는 AI 활용이 기본 역량처럼 자리 잡고 있는데, 정작... ",
			"bloggername":"더불어 사는 세상 이도형",
			"bloggerlink":"blog.naver.com\/anycall2502",
			"postdate":"20251114"
		},
		{
			"title":"학점은행제 <b>인공지능<\/b> 학위로 AI회사에 이직 성공했어요.",
			"link":"https:\/\/blog.naver.com\/seo8810603\/224226152116",
			"description":"저는 학점은행제 <b>인공지능<\/b> 학위로 이직까지 성공하게 된 30대 박ㅇ우입니다. 요즘 워낙 AI 기술이 많이... 솔직히 저도 처음에는 <b>인공지능<\/b>의 발전을 그렇게 달갑게 생각하진 않았어요. 사람의 일자리를... ",
			"bloggername":"Seo's reptile and Water life story",
			"bloggerlink":"blog.naver.com\/seo8810603",
			"postdate":"20260323"
		},
		{
			"title":"숙명여대 편입, <b>인공지능<\/b>공학부 합격까지 인서울 도전기",
			"link":"https:\/\/blog.naver.com\/spoly001\/224114522439",
			"description":"최근 IT와 AI 분야의 인재 양성에 주력하며 <b>인공지능<\/b>공학부를 신설해 미래 산업을 이끌어갈 여성 공학인 양성에 앞장서고 있습니다. 오늘은 실제로 숙명여대 <b>인공지능<\/b>공학부 편입에 성공한 학생의 생생한... ",
			"bloggername":"TV조선캠퍼스평생교육원 공식 블로그",
			"bloggerlink":"blog.naver.com\/spoly001",
			"postdate":"20251218"
		},
		{
			"title":"<b>인공지능<\/b> 교육 AI교육 키트 언플러그드 코딩 주미AI",
			"link":"https:\/\/blog.naver.com\/alley1980\/224229641240",
			"description":"<b>인공지능<\/b> 교육 AI교육 키트 언플러그드 코딩 주미AI 어느덧 따스한 바람이 부는 새학기 시즌이라 아이들 교육 문제로 고민이 많은 시기지요. 요즘은 학교 수업에서도 <b>인공지능<\/b> 교육 비중이 커지다 보니 집에서도... ",
			"bloggername":"고고씨네 소소한 일상",
			"bloggerlink":"blog.naver.com\/alley1980",
			"postdate":"20260325"
		},
		{
			"title":"[연수기록] <b>인공지능<\/b> 맞춤형 교수학습 플랫폼(AIEP) 전달연수",
			"link":"https:\/\/blog.naver.com\/dndus3356\/224196778376",
			"description":"<b>인공지능<\/b> 맞춤형 교수학습 플랫폼(AIEP) 전남 - 아이모두 학교 담당자 전달연수 홍혜민 선생님 지역별로... AIEP = <b>인공지능<\/b> 맞춤형 교수학습 플랫폼 작년에 전남교육청에서 이 플랫폼의 이름을 공모했던 기억이... ",
			"bloggername":"우연샘의 꿈꾸는 교실",
			"bloggerlink":"blog.naver.com\/dndus3356",
			"postdate":"20260226"
		},
		{
			"title":"<b>인공지능<\/b>(AI) 시대, 앞으로 일자리는 어떻게 변할까요?",
			"link":"https:\/\/blog.naver.com\/molab_suda\/224242653040",
			"description":"- ｢APEC 미래 일자리 포럼: <b>인공지능<\/b>(AI)와 인구구조 변화｣ 개최 - 산업전환 고용안정 기본계획... 이덕만 포스코 지능화센터장은 기존 수작업으로 진행하던 용광로 작업을, 데이터를 학습해 스스로 규칙을... ",
			"bloggername":"고용노동부 공식 블로그",
			"bloggerlink":"blog.naver.com\/molab_suda",
			"postdate":"20260406"
		},
		{
			"title":"알파벳(구글) 실적발표에서 <b>인공지능<\/b>(AI) 데이터센터 투자의... ",
			"link":"https:\/\/blog.naver.com\/hardark\/224172674993",
			"description":"<b>인공지능<\/b>(AI) 투자에 대한 현장의 생각과 현실을 이해하는데 큰 도움이 될 것같아 기록에 남기려고 합니다. 참고로 제 블로그를 꾸준히 보신 분들은 아시겠지만, 전 현 시점에서 연초에 <b>인공지능<\/b>(AI)와... ",
			"bloggername":"경제적 여유만큼 정신적 여유를",
			"bloggerlink":"blog.naver.com\/hardark",
			"postdate":"20260205"
		},
		{
			"title":"<b>인공지능<\/b> 자격증 취득방법 총정리",
			"link":"https:\/\/blog.naver.com\/wwevoszmffjq\/224063279444",
			"description":"<b>인공지능<\/b> 자격증 취득방법 총정리 그래픽 디자인을 전공하고 5년 동안 근무했던 회사에서 <b>인공지능<\/b> 자격증이 없다며 잘렸어요. 창작 관련 분야는 AI와 상관없을 줄 알았는데, ' AI 그림 ', ' 이미지 생성 도구... ",
			"bloggername":"왜 안 가인요?",
			"bloggerlink":"blog.naver.com\/wwevoszmffjq",
			"postdate":"20251103"
		}
	]
}

In [10]:
import os
import sys
import urllib.request
client_id = "Dy8QoalA82Rsb0srGFyN"
client_secret = "iP03VyF_LJ"
encText = urllib.parse.quote("인공지능")
url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과

start = 1
display = 20
rescode = 200
while rescode == 200 and start 100:

    new_url = url + f'&start={start}&display={display}'    
    request = urllib.request.Request(new_url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        print(response_body.decode('utf-8'))
        # print(f'crawl {start}')
    else:
        print("Error Code:" + rescode)

    start += display

crawl 1
crawl 101
crawl 201
crawl 301
crawl 401
crawl 501
crawl 601
crawl 701
crawl 801
crawl 901
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 400: Bad Request
Error : https://openapi.naver.com/v1/search/blog?query=%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5&start=1001&display=100
HTTP Error 429: Too Many Requests

KeyboardInterrupt:

In [ ]:
# 네이버 검색 API 예제 기반으로 네이버 검색 API 동작 방식 확인 (검색 결과 모두 받기)
# rescode가 200인 동안 start를 증가시켜서 계속 검색 (테스트를 위해 start는 25이하로 제한)

# 2. NaverNewsCrawler 개발
1. 네이버 뉴스 API로 Crawling : **crawlNaverNews(keyword)** -> 파이썬 json 데이터
1. 응답데이터를 리스트에 저장 : **mergeResultToList(result_list, merged_list)** -> List
1. 응답데이터가 없을 때까지 반복
1. 리스트를 CSV 파일로 저장 : **saveJSONListToCSV(merged_list, csv_filename)**

In [11]:
# 검색 API 호출, 응답을 JSON 데이터로 return하는 함수 작성
# API 호출 결과에 문제가 있을 경우 exception으로 처리
# exception 발생 시 exception과 호출 url 확인 (try : ... except Exception as e: ... )
import os
import sys
import urllib.request
import json
from time import sleep

def crawlNaverNews(keyword, start=1, display=10):

    client_id = "Dy8QoalA82Rsb0srGFyN"
    client_secret = "iP03VyF_LJ"
    encText = urllib.parse.quote("인공지능")
    url = "https://openapi.naver.com/v1/search/blog?query=" + encText # JSON 결과

    new_url = url + f'&start={start}&display={display}'    
    request = urllib.request.Request(new_url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        json_data = response_body.decode('utf-8')
        # print(f'crawl {start}')
        # json 문자열을 파이썬 객체로 변환
        py_data = json.loads(json_data)
        # print(py_data['items'])
        sleep(1)
        return py_data
    else:
        print("Error Code:" + rescode)
        return None

In [17]:
# 응답데이터를 리스트에 통합
def mergeResultToList(result_list, merged_list):
    for result in result_list:
        merged_list.append(result)

        
keyword = '인공지능'
start = 1
display = 10
merged_list = []
while start < 50:
    crawled_data = crawlNaverNews(keyword, start)
    mergeResultToList(crawled_data, merged_list)
    start += display

[{'title': '컴퓨터학원 실용적인 <b>인공지능</b> 수업과정', 'link': 'https://blog.naver.com/foryou1035/224160610941', 'description': '요즘 <b>인공지능</b>이 화두인데요. 처음에는 똑똑한 기능에 신기함이 컸지만, 시간이 갈수록 미묘한 감정이... 현재는 직장에서 <b>인공지능</b> 교육을 담당하게 되었고, 퇴근 후에는 취미로 웹사이트를 만들고 있어요.... ', 'bloggername': 'Ssong Story ♡', 'bloggerlink': 'blog.naver.com/foryou1035', 'postdate': '20260126'}, {'title': '<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리', 'link': 'https://blog.naver.com/gustlr00/224087574160', 'description': '<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리 “AI를 이해하는 사람과 그렇지 못한 사람의 차이가 점점 더 커지고 있다&quot;라는 말을 실감하게 되는 요즘, 직장 내에서도, 취업 시장에서도 <b>인공지능</b> 기술을 다룰... ', 'bloggername': '〃다시 만나는 그날 까지 〃', 'bloggerlink': 'blog.naver.com/gustlr00', 'postdate': '20251125'}, {'title': '<b>인공지능</b>전문가 자격증 취득과정 정리', 'link': 'https://blog.naver.com/anycall2502/224076021636', 'description': '<b>인공지능</b>전문가 자격증 취득과정 정리 최근 <b>인공지능</b> 기술이 눈에 띄게 발전하고 있다는 걸 느끼면서 뒤처지면 안 되겠다는 생각이 들었어요. 주변에서는 AI 활용이 기본 역량처럼 자리 잡고 있는데, 정작... ', 'bloggername': '더불어 사는 세상 이도형', 'bloggerlink': 'blog.naver.com/anycall2502', 'postdate': '20251114'}, {'title': '학점은행제 <b>인공지능</b> 학위로 AI회사에 이직 성공했어요.', 'link': 'https://blog.naver.com/seo8810603/224226152116', 'description': '저는 학점은행제 <b>인공지능</b> 학위로 이직까지 성공하게 된 30대 박ㅇ우입니다. 요즘 워낙 AI 기술이 많이... 솔직히 저도 처음에는 <b>인공지능</b>의 발전을 그렇게 달갑게 생각하진 않았어요. 사람의 일자리를... ', 'bloggername': "Seo's reptile and Water life story", 'bloggerlink': 'blog.naver.com/seo8810603', 'postdate': '20260323'}, {'title': '숙명여대 편입, <b>인공지능</b>공학부 합격까지 인서울 도전기', 'link': 'https://blog.naver.com/spoly001/224114522439', 'description': '최근 IT와 AI 분야의 인재 양성에 주력하며 <b>인공지능</b>공학부를 신설해 미래 산업을 이끌어갈 여성 공학인 양성에 앞장서고 있습니다. 오늘은 실제로 숙명여대 <b>인공지능</b>공학부 편입에 성공한 학생의 생생한... ', 'bloggername': 'TV조선캠퍼스평생교육원 공식 블로그', 'bloggerlink': 'blog.naver.com/spoly001', 'postdate': '20251218'}, {'title': '<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI', 'link': 'https://blog.naver.com/alley1980/224229641240', 'description': '<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI 어느덧 따스한 바람이 부는 새학기 시즌이라 아이들 교육 문제로 고민이 많은 시기지요. 요즘은 학교 수업에서도 <b>인공지능</b> 교육 비중이 커지다 보니 집에서도... ', 'bloggername': '고고씨네 소소한 일상', 'bloggerlink': 'blog.naver.com/alley1980', 'postdate': '20260325'}, {'title': '[연수기록] <b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전달연수', 'link': 'https://blog.naver.com/dndus3356/224196778376', 'description': '<b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전남 - 아이모두 학교 담당자 전달연수 홍혜민 선생님 지역별로... AIEP = <b>인공지능</b> 맞춤형 교수학습 플랫폼 작년에 전남교육청에서 이 플랫폼의 이름을 공모했던 기억이... ', 'bloggername': '우연샘의 꿈꾸는 교실', 'bloggerlink': 'blog.naver.com/dndus3356', 'postdate': '20260226'}, {'title': '<b>인공지능</b>(AI) 시대, 앞으로 일자리는 어떻게 변할까요?', 'link': 'https://blog.naver.com/molab_suda/224242653040', 'description': '- ｢APEC 미래 일자리 포럼: <b>인공지능</b>(AI)와 인구구조 변화｣ 개최 - 산업전환 고용안정 기본계획... 이덕만 포스코 지능화센터장은 기존 수작업으로 진행하던 용광로 작업을, 데이터를 학습해 스스로 규칙을... ', 'bloggername': '고용노동부 공식 블로그', 'bloggerlink': 'blog.naver.com/molab_suda', 'postdate': '20260406'}, {'title': '알파벳(구글) 실적발표에서 <b>인공지능</b>(AI) 데이터센터 투자의... ', 'link': 'https://blog.naver.com/hardark/224172674993', 'description': '<b>인공지능</b>(AI) 투자에 대한 현장의 생각과 현실을 이해하는데 큰 도움이 될 것같아 기록에 남기려고 합니다. 참고로 제 블로그를 꾸준히 보신 분들은 아시겠지만, 전 현 시점에서 연초에 <b>인공지능</b>(AI)와... ', 'bloggername': '경제적 여유만큼 정신적 여유를', 'bloggerlink': 'blog.naver.com/hardark', 'postdate': '20260205'}, {'title': '<b>인공지능</b> 자격증 취득방법 총정리', 'link': 'https://blog.naver.com/wwevoszmffjq/224063279444', 'description': "<b>인공지능</b> 자격증 취득방법 총정리 그래픽 디자인을 전공하고 5년 동안 근무했던 회사에서 <b>인공지능</b> 자격증이 없다며 잘렸어요. 창작 관련 분야는 AI와 상관없을 줄 알았는데, ' AI 그림 ', ' 이미지 생성 도구... ", 'bloggername': '왜 안 가인요?', 'bloggerlink': 'blog.naver.com/wwevoszmffjq', 'postdate': '20251103'}]
[{'title': '26년 봄방학 방문한 곳들 (서울로봇<b>인공지능</b>과학관... ', 'link': 'https://blog.naver.com/rachmaninoff5/224219543273', 'description': '서울로봇<b>인공지능</b>과학관 (RAIM) ️ 사전 예약: 매월 10일 오전 10시, 서울시 공공서비스예약 시스템에서... 아이와 방학 동안 로봇, <b>인공지능</b>, 우주를 생각지도 않은 곳에서 접하다보니 시대가 변하긴 변했나? 라는... ', 'bloggername': '광화문 나그네의 만화경', 'bloggerlink': 'blog.naver.com/rachmaninoff5', 'postdate': '20260317'}, {'title': 'AI학원, <b>인공지능</b> 전문가로 성장하는 가장 빠른 방법', 'link': 'https://blog.naver.com/himediacokr/224231103099', 'description': '최근 AI 대전환이라 느껴질 만큼 우리 주변의 모든 산업이 <b>인공지능</b>을 중심으로 재편되고 있습니다. 챗... ✔️ 실전 모델 구현 인간의 뇌를 닮은 모델을 구축하는, 딥러닝과 인공신경망에 대해 배우게 됩니다.... ', 'bloggername': '하이미디어 아카데미 공식블로그', 'bloggerlink': 'blog.naver.com/himediacokr', 'postdate': '20260327'}, {'title': '생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교', 'link': 'https://blog.naver.com/teamlinchpin/224177479277', 'description': "생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교 요즘 뉴스, 업무, 공부, 콘텐츠 제작까지 어디를 가도 빠지지 않고 등장하는 단어가 있습니다. 바로 '생성형 <b>인공지능</b>(AI)'인데요. &quot;AI가 사람처럼... ", 'bloggername': '온라인마케팅, 린치핀기획', 'bloggerlink': 'blog.naver.com/teamlinchpin', 'postdate': '20260209'}, {'title': '<b>인공지능</b>전문가 자격증 취득방법 총정리', 'link': 'https://blog.naver.com/gustlr00/224076037551', 'description': '<b>인공지능</b>전문가 자격증 취득방법 총정리 요즘 AI 관련 뉴스가 하루가 다르게 쏟아지다 보니까, 저도 이... 그래서 장기적인 커리어 준비 차원에서 <b>인공지능</b>전문가 자격증 과정을 본격적으로 찾아보기... ', 'bloggername': '〃다시 만나는 그날 까지 〃', 'bloggerlink': 'blog.naver.com/gustlr00', 'postdate': '20251114'}, {'title': '학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자)', 'link': 'https://blog.naver.com/jje423/224228420448', 'description': '학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자) 안녕하세요! 4년제 대학을 졸업하고도 전공... 그러다 우리 일상 곳곳에 스며든 <b>인공지능</b>(AI) 분야를 보며 &quot;지금이라도 이 길을 준비하면 늦지 않을까?... ', 'bloggername': '욕심많은 별들맘 이야기', 'bloggerlink': 'blog.naver.com/jje423', 'postdate': '20260325'}, {'title': '직장인 Ai 활용 능력 기르는 <b>인공지능</b> 학사학위', 'link': 'https://blog.naver.com/seo8810603/224224382865', 'description': '과정으로 <b>인공지능</b> 공학으로 4년제 학사학위를 취득했어요. 온라인으로 학벌을 개선하는 이 방식이... 제가 준비한 학점은행제 <b>인공지능</b>학은 학교 출석업싱 온라인 과정으로 진행됐어요. 저는 4년제 대학을... ', 'bloggername': "Seo's reptile and Water life story", 'bloggerlink': 'blog.naver.com/seo8810603', 'postdate': '20260321'}, {'title': '학점은행제 <b>인공지능</b> 온라인으로 학위 취득했어요', 'link': 'https://blog.naver.com/reebbang/224181846192', 'description': '저는 비전공자로 직장 생활을 하다가 미래를 위해 학점은행제 <b>인공지능</b> 전공을 통해 학사학위를 취득했던 20대 남성입니다. 처음에는 솔직히 <b>인공지능</b>이라는 단어가 너무 막연하게 느껴졌습니다. &quot;AI가... ', 'bloggername': "30's Mood", 'bloggerlink': 'blog.naver.com/reebbang', 'postdate': '20260213'}, {'title': "'만화로 배우는 AI <b>인공지능</b>' 소개 및 후기", 'link': 'https://blog.naver.com/whruddlf75/224159351443', 'description': "'만화로 배우는 AI <b>인공지능</b>' 소개 만화로 배우는 AI <b>인공지능</b> 미야케 요이치로.전승민 감수, 비젠 야스노리 그림, 신은주 옮김2023비전코리아 미야케 요이치로 지금 전승민 감수의 '만화로 배우는 AI... ", 'bloggername': '혼노리', 'bloggerlink': 'blog.naver.com/whruddlf75', 'postdate': '20260331'}, {'title': '<b>인공지능</b> 개발자 : AI 직무의 취업 준비 공략법', 'link': 'https://blog.naver.com/urmyver/224196997312', 'description': '<b>인공지능</b> 개발자 AI 직무의 취업 준비 공략법 2020년대 초반 때까지만 하더라도 대다수의 사람들은 수준 높은 <b>인공지능</b>을 구현하는 것은 불가능한 것은 아니지만, 빠른 시일 내에 개발하는 것은 어려울 것... ', 'bloggername': '주들의 그리 대단하진 않지만 굉장한 이야기', 'bloggerlink': 'blog.naver.com/urmyver', 'postdate': '20260226'}, {'title': '최소한의 수학』 <b>인공지능</b>을 이해하는 가장 현실적인 방법', 'link': 'https://blog.naver.com/sandhya/224206770826', 'description': 'AI가 쉬워지는 최소한의 수학 이동준2026지상의책(갈매나무) 사람들은 <b>인공지능</b>을 이야기할 때 종종... <b>인공지능</b>은 요술 상자처럼 느껴지기도 한다. 질문을 던지면 답을 내놓고, 사진을 보여주면 내용을 설명하고... ', 'bloggername': '밀크티 책세상', 'bloggerlink': 'blog.naver.com/sandhya', 'postdate': '20260306'}]
[{'title': '<b>인공지능</b>(AI)로 진화하는 산재보험...근로복지공단 ’K... ', 'link': 'https://blog.naver.com/molab_suda/224229343408', 'description': '- 대한민국 <b>인공지능</b>(AI) 10대 선도기관 선정, 클라우드 네이티브 전환 우수사례 인정 - <b>인공지능</b>(AI)재해조사·치료예측·장해판정·일자리추천...산재보험 <b>인공지능</b>(AI) 전환 본격화 근로복지공단(이사장... ', 'bloggername': '고용노동부 공식 블로그', 'bloggerlink': 'blog.naver.com/molab_suda', 'postdate': '20260325'}, {'title': '최소한의 수학』 <b>인공지능</b>을 이해하는 가장 현실적인 방법', 'link': 'https://blog.naver.com/sandhya/224206770826', 'description': 'AI가 쉬워지는 최소한의 수학 이동준2026지상의책(갈매나무) 사람들은 <b>인공지능</b>을 이야기할 때 종종... <b>인공지능</b>은 요술 상자처럼 느껴지기도 한다. 질문을 던지면 답을 내놓고, 사진을 보여주면 내용을 설명하고... ', 'bloggername': '밀크티 책세상', 'bloggerlink': 'blog.naver.com/sandhya', 'postdate': '20260306'}, {'title': '<b>인공지능</b> 시대의 교육 격차와 새로운 인재상에 대한 고찰', 'link': 'https://blog.naver.com/vizensoft/224218298881', 'description': '<b>인공지능</b> 기술이 일상과 산업 전반에 깊숙이 자리 잡으면서 교육 현장에서도 근본적인 변화가... <b>인공지능</b> 교육의 접근성 격차와 환경의 중요성 <b>인공지능</b> 시대에 접어들며 교육 현장에서는 새로운 형태의... ', 'bloggername': '비젠소프트 홈페이지제작 웹에이전시 BLOG', 'bloggerlink': 'blog.naver.com/vizensoft', 'postdate': '20260316'}, {'title': '경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기', 'link': 'https://blog.naver.com/xavisnet/224220577252', 'description': '경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기 안녕하세요, 자비스넷입니다. 오늘은 경기 용인에 위치한 냉동창고 현장에 <b>인공지능</b> 적외선 CCTV 4대를 설치한 후기를 공유해드릴게요. 냉동창고나... ', 'bloggername': 'XAVISnet', 'bloggerlink': 'blog.naver.com/xavisnet', 'postdate': '20260318'}, {'title': '[고용노동부] 지청 <b>인공지능</b>(AI) 활용 교육', 'link': 'https://blog.naver.com/ahnbh334/224200193453', 'description': '이번 강의에서는 지청장님의 특별한 관심과 배려 속에 <b>인공지능</b>에 대한 운영현황과 발전방향에 대하여 소개했는데 정부의 <b>인공지능</b>에 대한 발전 정책 때문인지 공무원들의 관심 또한 민간 못지않게... ', 'bloggername': 'KPMC 공식 블로그', 'bloggerlink': 'blog.naver.com/ahnbh334', 'postdate': '20260301'}, {'title': '서울시립대 <b>인공지능</b>학과, 코딩만 하는 학과가 아닌 이유', 'link': 'https://blog.naver.com/cjs1748/224218018893', 'description': '서울시립대 <b>인공지능</b>학과, 코딩만 하는 학과가 아닌 이유 서울시립대 <b>인공지능</b>학과를 검색하는 분들이 가장 많이 막히는 지점이 ai는 코딩만 잘하면 되지 않나 아니면 수학, 윤리, 현장 문제까지 함께 봐야 할... ', 'bloggername': '스터디팩트 생활정보 이야기', 'bloggerlink': 'blog.naver.com/cjs1748', 'postdate': '20260316'}, {'title': '<b>인공지능</b> 시대의 게임 체인저, AI전문트랙의 가치', 'link': 'https://blog.naver.com/himediacokr/224234669618', 'description': '단순한 코딩 능력이 아닌, 데이터에서 인사이트를 추출하고 이를 기반으로 <b>인공지능</b> 모델을 설계 및... ✔️ 딥러닝 및 신경망 최적화 인간의 뇌 구조를 모사한 인공신경망의 원리를 배우고, 텐서플로나... ', 'bloggername': '하이미디어 아카데미 공식블로그', 'bloggerlink': 'blog.naver.com/himediacokr', 'postdate': '20260330'}, {'title': 'AI가 위협하는 직업은 무엇일까 #<b>인공지능</b>일자리', 'link': 'https://blog.naver.com/eterna01/224219200381', 'description': '최근 몇 년 동안 <b>인공지능</b>(AI)은 우리의 일과 직업 세계를 빠르게 바꾸고 있습니다. 특히 챗봇... 오늘의 핵심 영어 단어 20개 Artificial Intelligence – <b>인공지능</b> Threatened – 위협받는 Adapt – 적응하다... ', 'bloggername': 'Jer 29:11', 'bloggerlink': 'blog.naver.com/eterna01', 'postdate': '20260317'}, {'title': '[챗지피티 교육] &quot;생성형 <b>인공지능</b> 활용, 프롬프트 및 보고서... ', 'link': 'https://blog.naver.com/hijunggon/224240732080', 'description': "세종특별자치시교육청의 지방공무원분들을 대상으로 '생성형 <b>인공지능</b>(ChatGPT) 활용, 프롬프트 및... 본 과정은 챗지피티(ChatGPT)를 비롯한 다양한 생성형 <b>인공지능</b> 도구의 활용법을 학습하여 실제 업무에... ", 'bloggername': '김정곤의 강연노트', 'bloggerlink': 'blog.naver.com/hijunggon', 'postdate': '20260404'}, {'title': '안전은 높이고! 부산시 <b>인공지능</b>(AI) 기반 교통관리시스템 도입', 'link': 'https://blog.naver.com/cooolbusan/224227464918', 'description': '부산광역시(시장 박형준)는 시민이 일상에서 직접 체감하는 교통 편의를 높이기 위해 <b>인공지능</b>(AI)과 교통데이터를 접목한 지능형 교통 신호체계 고도화를 본격적으로 추진합니다. 번 사업은 스마트빌리지... ', 'bloggername': '부산광역시 대표 블로그', 'bloggerlink': 'blog.naver.com/cooolbusan', 'postdate': '20260324'}]
[{'title': '오토캐드 AI, <b>인공지능</b> 덕분에 편한 2026 AutoCAD AI... ', 'link': 'https://blog.naver.com/iffu/224222483958', 'description': '요즘은 어떤 서비스를 사용할 때 <b>인공지능</b> 기능들을 정말 필수적이라고 할 수 있습니다. 이러한 AI... 기능들에 <b>인공지능</b>이 가미되어 더 편하고 효율적으로 캐드 작업을 할 수 있게 하고 있다는 점이... ', 'bloggername': "이퓨의 IT's IT", 'bloggerlink': 'blog.naver.com/iffu', 'postdate': '20260320'}, {'title': 'AI교육 <b>인공지능</b> 활용능력에 대하여', 'link': 'https://blog.naver.com/ljshhj/224147887778', 'description': '본 포스팅은 업체로부터 원고료를 받아 작성되었습니다 AI교육 <b>인공지능</b> 활용능력에 대하여 AI, <b>인공지능</b>은 챗지피티처럼 질문하고 답변하는 걸 넘어서 사진이나 영상 등을 합성하고 업무를 도와줄 만큼... ', 'bloggername': '떠나자닷컴', 'bloggerlink': 'blog.naver.com/ljshhj', 'postdate': '20260115'}, {'title': '발달장애 학생을 위한 맞춤형 <b>인공지능</b>(AI) 학습 시대 열린다', 'link': 'https://blog.naver.com/moeblog/224212332128', 'description': '교육부, 발달장애 학생의 학습 특성을 고려한 ‘<b>인공지능</b>(AI)·디지털 교육자료’ 신학기 본격 보급 첨부파일 [교육부 03-12(목) 조간보도자료] 발달장애 학생을 위한 맞춤형 <b>인공지능</b>(AI) 학습 시대 열린다.pdf... ', 'bloggername': '교육부', 'bloggerlink': 'blog.naver.com/moeblog', 'postdate': '20260311'}, {'title': '국립광주과학관 [2026 전국민 <b>인공지능</b>(AI) 창작 경진대회] 안내', 'link': 'https://blog.naver.com/sciencenter/224231614689', 'description': '참가분야 <b>인공지능</b> 창작 도구를 활용한 그림 및 로고송 접수기간 4. 20.(월) ~ 6. 30.(화), 18:00 접수방법 참가신청서 및 동의서, 작품(그림 또는 음원) 파일제출 후원 한국지능정보사회진흥원(NIA) 문의처... ', 'bloggername': '국립광주과학관님의 블로그', 'bloggerlink': 'blog.naver.com/sciencenter', 'postdate': '20260331'}, {'title': '<b>인공지능</b> 데이터센터와, 속도를 만드는 메모리 반도체', 'link': 'https://blog.naver.com/with_msip/224163789021', 'description': '<b>인공지능</b>은 기존 IT 서버보다 더 많은 연산을 요구합니다. 기존 컴퓨팅 기술처럼 계산만 하는 것이... 메모리의 성능이 곧 <b>인공지능</b>의 성능과 인프라 개선으로 이어진다는 사실 알고 계셨나요? 금만큼 귀해진... ', 'bloggername': '과학기술정보통신부 블로그', 'bloggerlink': 'blog.naver.com/with_msip', 'postdate': '20260204'}, {'title': '[디지털캠프] <b>인공지능</b>(AI) 작곡 탐사대는 무슨 프로그램일까?', 'link': 'https://blog.naver.com/dalkkum_plus/224242871976', 'description': "단연 '생성형 <b>인공지능</b>(AI)'입니다. 하지만 단순한 체험을 넘어, 학생들의 사고력을 확장하고 실제 결과물까지 도출할 수 있는 프로그램을 찾기는 쉽지 않습니다. 저희 디지털캠프 '<b>인공지능</b>(AI) 작곡 탐사대는... ", 'bloggername': '달꿈 공식 블로그', 'bloggerlink': 'blog.naver.com/dalkkum_plus', 'postdate': '20260406'}, {'title': '제자들은 자란다(<b>인공지능</b> 융합수업 가이드)', 'link': 'https://blog.naver.com/odelmio/224235370118', 'description': '제자들은 자란다(<b>인공지능</b> 융합수업 가이드) 2026 03 31 화 학교에 있으면서 나이듦을 실감하기 시작하는... 오한나, &lt;<b>인공지능</b> 융합수업 가이드: 챗GPT, AIVA, 구글을 활용한 미래 음악 교실&gt;(다빈치북스, 2023)... ', 'bloggername': '모르는 요셉', 'bloggerlink': 'blog.naver.com/odelmio', 'postdate': '20260331'}, {'title': 'AI 국부론 책 후기 AGI 뜻 약자 영어줄임말 (범용<b>인공지능</b>)', 'link': 'https://blog.naver.com/babydreamer5/224221388090', 'description': '특정 작업 하나만 잘하는 <b>인공지능</b>이 아니라, 인간처럼 여러 문제를 폭넓게 이해하고 새로운 상황에도 적용할 수 있는 지능을 뜻해요. 사실 지금의 많은 AI는 번역, 요약, 이미지 생성, 검색 보조처럼 특정... ', 'bloggername': '영어뉴스와 미드영어', 'bloggerlink': 'blog.naver.com/babydreamer5', 'postdate': '20260318'}, {'title': '[현장한컷] <b>인공지능</b> 혁신기업 현장 방문', 'link': 'https://blog.naver.com/ppspr/224235764773', 'description': '<b>인공지능</b>(AI) 재활용 선별 로봇, <b>인공지능</b> 사물인터넷(AIoT) 스마트 안심 화장실 등 혁신기술 현장 방문  혁신제품 시범구매·글로벌 실증 지원을 통해 딥테크 기업 성장 가속화 강성민 조달청 차장은 3월 31일... ', 'bloggername': '조달청 블로그', 'bloggerlink': 'blog.naver.com/ppspr', 'postdate': '20260331'}, {'title': '공교육에 <b>인공지능</b> 교육이 필요한 이유', 'link': 'https://blog.naver.com/hamamath_/224218126842', 'description': '공교육에 <b>인공지능</b> 교육이 필요한 이유 교육부 AI 교육 확대 정책이 시사하는 변화 교육부가 초·중등 <b>인공지능</b> 교육 담당 교원 역량 강화 연수 과정을 개발하고 본격적인 운영에 들어간다는 발표는 단순한... ', 'bloggername': '수학문해력', 'bloggerlink': 'blog.naver.com/hamamath_', 'postdate': '20260316'}]
[{'title': '[육아일기] 경북교육청 발명<b>인공지능</b>교육원', 'link': 'https://blog.naver.com/zz_anna/224232565522', 'description': '#따빛샘 #육아일기 경주 황리단길 한복판에 위치한:) #경상북도 #발명<b>인공지능</b>교육원 원래... #발명<b>인공지능</b>교육원 주관 부스6개 #메이커교육관 부스 2개 #<b>인공지능</b>교육관 부스 3개 표정으로 인형뽑기와 AI와... ', 'bloggername': '따빛의 일기장', 'bloggerlink': 'blog.naver.com/zz_anna', 'postdate': '20260328'}, {'title': '울산교육청, <b>인공지능</b>으로 행정 효율 높여', 'link': 'https://blog.naver.com/us_edu/224242791797', 'description': '- 전국 최초 업무 자동화 센터 본격 운영 - 단순 행정업무 자동화로 업무 부담 줄여 울산광역시교육청(교육감 천창수)은 전국 시도교육청 가운데 처음으로 <b>인공지능</b> 기술을 접목한 ‘업무 자동화 <b>인공지능</b>(AI)... ', 'bloggername': '울산광역시교육청', 'bloggerlink': 'blog.naver.com/us_edu', 'postdate': '20260406'}, {'title': '머신러닝전문가 교육정보 <b>인공지능</b>융합학과에서 공부해요', 'link': 'https://blog.naver.com/ocublog/224192322874', 'description': '머신러닝은 데이터를 기반으로 <b>인공지능</b> 모델을 설계하고 학습, 배포 등을 하는 직업인 만큼 미래... 머신러닝 전문가가 되기 위한 과정을 밟을 수 있는 <b>인공지능</b>융합학과를 소개해 드립니다. 머신러닝에... ', 'bloggername': '일과 학업을 동시에! 한국열린사이버대학교!', 'bloggerlink': 'blog.naver.com/ocublog', 'postdate': '20260223'}, {'title': '[민간자격] <b>인공지능</b>(AI) 활용 블랙벨트', 'link': 'https://blog.naver.com/ahnbh334/224213227765', 'description': '최근 전 세계적으로 <b>인공지능</b>(AI)에 대한 관심이 빠르게 확산되고 있습니다. 개인의 업무 생산성... 2일 16시간 집중 커리큘럼 따라서 KPMC는 이달 3월 21~22일(주말과정), 진행하는 &quot;<b>인공지능</b>(AI) 활용 블랙벨트... ', 'bloggername': 'KPMC 공식 블로그', 'bloggerlink': 'blog.naver.com/ahnbh334', 'postdate': '20260312'}, {'title': '대구 중구 진로진학지원센터 <b>인공지능</b> 시대 우리 아이의... ', 'link': 'https://blog.naver.com/dgjunggu/224242246425', 'description': "대구 중구 진로진학지원센터 <b>인공지능</b> 시대 우리 아이의 미래는? 특별 강연 안내 요즘 '<b>인공지능</b>(AI)'라는 단어 하루에도 몇 번씩 듣게 되죠. ChatGPT부터 자율주행, AI 그림까지 기술의 변화 속도가 정말 빠르게... ", 'bloggername': '대구광역시 중구청 공식블로그', 'bloggerlink': 'blog.naver.com/dgjunggu', 'postdate': '20260406'}, {'title': '교육부, 초·중등 <b>인공지능</b> 교육 담당교원을 위한 연수과정... ', 'link': 'https://blog.naver.com/moeblog/224218006604', 'description': '초등 교원, 중등 정보, 고교 ‘<b>인공지능</b> 수학’ 교과 담당 교원을 위한 맞춤형 <b>인공지능</b> 교육 연수 체계 구축 기초-심화-전문 단계 멀티트랙 구조로 2026년 5월 기초 단계 연수 시작, 2029년까지 1만 명 이수... ', 'bloggername': '교육부', 'bloggerlink': 'blog.naver.com/moeblog', 'postdate': '20260316'}, {'title': '[486] <b>인공지능</b>시대 철학수업 (박시몽)', 'link': 'https://blog.naver.com/jckwb66/224236464116', 'description': '답을 찾고자 하면 깊이 생각하기 보다는 <b>인공지능</b>에게 질문하는 횟수들이 늘어나다보니 스스로 오래... 질문으로 답을 찾는 <b>인공지능</b> 시대 철학 수업 박시몽2026한언 철학이란 어렵게만 느껴지지만 샘은... ', 'bloggername': '백여샘의 진로이야기', 'bloggerlink': 'blog.naver.com/jckwb66', 'postdate': '20260401'}, {'title': '[책을펴다] AI로 미래를 설계하는 서울<b>인공지능</b>고등학교', 'link': 'https://blog.naver.com/seouledu2012/224242405941', 'description': "3월의 책을 펴다는 AI로 미래를 설계하는 '서울<b>인공지능</b>고등학교'에서 시작합니다. 혼자 읽던 이야기가... 미디어 콘텐츠 AI 프롬프트 디자인 &quot;AI콘텐츠디자인과인 저에게, <b>인공지능</b>을 활용한 콘텐츠 제작의... ", 'bloggername': '서울교육블로그', 'bloggerlink': 'blog.naver.com/seouledu2012', 'postdate': '20260406'}, {'title': '바둑 로봇 AI <b>인공지능</b> 바둑판 세트 이런 분께 추천', 'link': 'https://blog.naver.com/sjrnfl81/224206852844', 'description': 'AI <b>인공지능</b> 바둑로봇이라니, 처음엔 어떻게 작동하는지 궁금하더라고요. 요즘 바둑 학습 도구로... AI <b>인공지능</b> 바둑로봇, 어떤 제품인가요? AI <b>인공지능</b> 바둑로봇은 사람 대신 바둑을 두어주는 스마트 바둑판... ', 'bloggername': '또 다른 세상', 'bloggerlink': 'blog.naver.com/sjrnfl81', 'postdate': '20260306'}, {'title': 'AI책 추천 슈퍼휴먼 슈퍼워크 <b>인공지능</b> 시대 일하는 법', 'link': 'https://blog.naver.com/limhyunae/224222765253', 'description': '슈퍼워크 <b>인공지능</b> 시대 일하는 법 최근 AI 관련 책을 찾다가 읽게 된 슈퍼휴먼 슈퍼워크는 단순한 AI 활용법을 넘어 앞으로어떻게 일해야 하는가를 생각하게 만든 책이었어요. 요즘 AI책이나 <b>인공지능</b>책이... ', 'bloggername': '달달한 그녀의 일상', 'bloggerlink': 'blog.naver.com/limhyunae', 'postdate': '20260319'}]

In [ ]:
# 검색어 입력
keyword = '인공지능'

# API 호출 결과 전송된 JSON이 없거나, 전송된 JSON에 검색 결과가 없을 때까지
# 검색 결과를 JSON의 list로 저장 후 검색 API 추가 호출


# 검색 결과를 저장할 list 초기화
resultAll = []

# 첫 검색 API 호출 데이터 초기화
start = 1
display = 10

while True:
    crawled_data = crawlNaverNews(keyword, start)
    # API 호출 성공 여부 출력
    if crawled_data:
        print(f'{keyword} [{start}] : 검색 성공')
    else:
        print(f'{keyword} [{start}] : 검색 실패')
        break
    
    # crawling된 데이터가 없으면 중지

    # 응답데이터 정리하여 리스트로 통합
    mergeResultToList(crawled_data, merged_list)
    # 다음 검색 API 호출을 위한 파라미터 조정
    start += display
            

# 리스트를 csv 파일로 저장

In [1]:
# JSON의 list를 dataframe으로 변환하여 csv 파일로 저장

In [14]:
keyword = '인공지능'
start = 1
resultAll = []
while start < 20:
    
    crawled_data = crawlNaverNews(keyword, start)
    if crawled_data:
        #print(crawled_data)
        print('crawling 성공:', start)
        resultAll += crawled_data['items']
        start += 10
    else:
        print('crawling 실패:', start)
        break

# dictionary의 list

crawling 성공: 1
crawling 성공: 11

In [15]:
resultAll[:2]

[{'title': '컴퓨터학원 실용적인 <b>인공지능</b> 수업과정',
  'link': 'https://blog.naver.com/foryou1035/224160610941',
  'description': '요즘 <b>인공지능</b>이 화두인데요. 처음에는 똑똑한 기능에 신기함이 컸지만, 시간이 갈수록 미묘한 감정이... 현재는 직장에서 <b>인공지능</b> 교육을 담당하게 되었고, 퇴근 후에는 취미로 웹사이트를 만들고 있어요.... ',
  'bloggername': 'Ssong Story ♡',
  'bloggerlink': 'blog.naver.com/foryou1035',
  'postdate': '20260126'},
 {'title': '<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리',
  'link': 'https://blog.naver.com/gustlr00/224087574160',
  'description': '<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리 “AI를 이해하는 사람과 그렇지 못한 사람의 차이가 점점 더 커지고 있다&quot;라는 말을 실감하게 되는 요즘, 직장 내에서도, 취업 시장에서도 <b>인공지능</b> 기술을 다룰... ',
  'bloggername': '〃다시 만나는 그날 까지 〃',
  'bloggerlink': 'blog.naver.com/gustlr00',
  'postdate': '20251125'}]

In [17]:
import pandas as pd
data_df = pd.DataFrame(resultAll)
# result_file_name = 
data_df.to_csv(f'./data/{keyword}_naver_news.csv')

In [18]:
# 저장한 파일을 dataframe으로 loading 해보기
loaded_data_df = pd.read_csv(f'./data/{keyword}_naver_news.csv', index_col = 0)
loaded_data_df

,title,link,description,bloggername,bloggerlink,postdate
0,컴퓨터학원 실용적인 <b>인공지능</b> 수업과정,https://blog.naver.com/foryou1035/224160610941,"요즘 <b>인공지능</b>이 화두인데요. 처음에는 똑똑한 기능에 신기함이 컸지만, ...",Ssong Story ♡,blog.naver.com/foryou1035,20260126
1,<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리,https://blog.naver.com/gustlr00/224087574160,<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리 “AI를 이해하는 사람과 ...,〃다시 만나는 그날 까지 〃,blog.naver.com/gustlr00,20251125
2,<b>인공지능</b>전문가 자격증 취득과정 정리,https://blog.naver.com/anycall2502/224076021636,<b>인공지능</b>전문가 자격증 취득과정 정리 최근 <b>인공지능</b> 기술이 ...,더불어 사는 세상 이도형,blog.naver.com/anycall2502,20251114
3,학점은행제 <b>인공지능</b> 학위로 AI회사에 이직 성공했어요.,https://blog.naver.com/seo8810603/224226152116,저는 학점은행제 <b>인공지능</b> 학위로 이직까지 성공하게 된 30대 박ㅇ우입니...,Seo's reptile and Water life story,blog.naver.com/seo8810603,20260323
4,"숙명여대 편입, <b>인공지능</b>공학부 합격까지 인서울 도전기",https://blog.naver.com/spoly001/224114522439,최근 IT와 AI 분야의 인재 양성에 주력하며 <b>인공지능</b>공학부를 신설해 ...,TV조선캠퍼스평생교육원 공식 블로그,blog.naver.com/spoly001,20251218
5,엘지 LG 통돌이 세탁기 추천 용량 17kg <b>인공지능</b> T17WX3,https://blog.naver.com/reser45/224246855986,기술의 발전은 여기서 그치지 않고 <b>인공지능</b> AI과 결합되었습니다. LG...,무스미엘,blog.naver.com/reser45,20260409
6,<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI,https://blog.naver.com/alley1980/224229641240,<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI 어느덧 따스한 바...,고고씨네 소소한 일상,blog.naver.com/alley1980,20260325
7,[연수기록] <b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전달연수,https://blog.naver.com/dndus3356/224196778376,<b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전남 - 아이모두 학교 담당...,우연샘의 꿈꾸는 교실,blog.naver.com/dndus3356,20260226
8,<b>인공지능</b> 자격증 취득방법 총정리,https://blog.naver.com/wwevoszmffjq/224063279444,<b>인공지능</b> 자격증 취득방법 총정리 그래픽 디자인을 전공하고 5년 동안 근...,왜 안 가인요?,blog.naver.com/wwevoszmffjq,20251103
9,"<b>인공지능</b>(AI) 시대, 앞으로 일자리는 어떻게 변할까요?",https://blog.naver.com/molab_suda/224242653040,- ｢APEC 미래 일자리 포럼: <b>인공지능</b>(AI)와 인구구조 변화｣ 개...,고용노동부 공식 블로그,blog.naver.com/molab_suda,20260406
10,경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기,https://blog.naver.com/xavisnet/224220577252,"경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기 안녕하세요, 자...",XAVISnet,blog.naver.com/xavisnet,20260318
11,"생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교",https://blog.naver.com/teamlinchpin/224177479277,"생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교 요즘 뉴스,...","온라인마케팅, 린치핀기획",blog.naver.com/teamlinchpin,20260209
12,"AI학원, <b>인공지능</b> 전문가로 성장하는 가장 빠른 방법",https://blog.naver.com/himediacokr/224231103099,최근 AI 대전환이라 느껴질 만큼 우리 주변의 모든 산업이 <b>인공지능</b>을 ...,하이미디어 아카데미 공식블로그,blog.naver.com/himediacokr,20260327
13,<b>인공지능</b>전문가 자격증 취득방법 총정리,https://blog.naver.com/gustlr00/224076037551,<b>인공지능</b>전문가 자격증 취득방법 총정리 요즘 AI 관련 뉴스가 하루가 다...,〃다시 만나는 그날 까지 〃,blog.naver.com/gustlr00,20251114
14,"학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자)",https://blog.naver.com/jje423/224228420448,"학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자) 안녕하세요! 4...",욕심많은 별들맘 이야기,blog.naver.com/jje423,20260325
15,직장인 Ai 활용 능력 기르는 <b>인공지능</b> 학사학위,https://blog.naver.com/seo8810603/224224382865,과정으로 <b>인공지능</b> 공학으로 4년제 학사학위를 취득했어요. 온라인으로 학...,Seo's reptile and Water life story,blog.naver.com/seo8810603,20260321
16,몰트북 충격 읽어보니 AI 시대 얼마나 바뀔까 <b>인공지능</b> 책 추천,https://blog.naver.com/limhyunae/224248225786,몰트북 충격 읽어보니 AI 시대 얼마나 바뀔까 <b>인공지능</b> 책 추천 요즘 ...,달달한 그녀의 일상,blog.naver.com/limhyunae,20260410
17,학점은행제 <b>인공지능</b> 온라인으로 학위 취득했어요,https://blog.naver.com/reebbang/224181846192,저는 비전공자로 직장 생활을 하다가 미래를 위해 학점은행제 <b>인공지능</b> 전...,30's Mood,blog.naver.com/reebbang,20260213
18,최소한의 수학』 <b>인공지능</b>을 이해하는 가장 현실적인 방법,https://blog.naver.com/sandhya/224206770826,AI가 쉬워지는 최소한의 수학 이동준2026지상의책(갈매나무) 사람들은 <b>인공지...,밀크티 책세상,blog.naver.com/sandhya,20260306
19,"NVIDIA GTC 2026에서 본 <b>인공지능</b> 반도체의 미래! GPU, ...",https://blog.naver.com/nststory2014/224251065664,"<b>인공지능</b> 기술은 단순한 알고리즘 경쟁을 넘어, 실제 구현과 운영을 포함...",국가과학기술연구회,blog.naver.com/nststory2014,20260414

In [19]:
loaded_data_df2 = pd.read_csv(f'./data/{keyword}_naver_news.csv')
loaded_data_df2

,Unnamed: 0,title,link,description,bloggername,bloggerlink,postdate
0,0,컴퓨터학원 실용적인 <b>인공지능</b> 수업과정,https://blog.naver.com/foryou1035/224160610941,"요즘 <b>인공지능</b>이 화두인데요. 처음에는 똑똑한 기능에 신기함이 컸지만, ...",Ssong Story ♡,blog.naver.com/foryou1035,20260126
1,1,<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리,https://blog.naver.com/gustlr00/224087574160,<b>인공지능</b> 자격증 취득과정 및 취업 정보 정리 “AI를 이해하는 사람과 ...,〃다시 만나는 그날 까지 〃,blog.naver.com/gustlr00,20251125
2,2,<b>인공지능</b>전문가 자격증 취득과정 정리,https://blog.naver.com/anycall2502/224076021636,<b>인공지능</b>전문가 자격증 취득과정 정리 최근 <b>인공지능</b> 기술이 ...,더불어 사는 세상 이도형,blog.naver.com/anycall2502,20251114
3,3,학점은행제 <b>인공지능</b> 학위로 AI회사에 이직 성공했어요.,https://blog.naver.com/seo8810603/224226152116,저는 학점은행제 <b>인공지능</b> 학위로 이직까지 성공하게 된 30대 박ㅇ우입니...,Seo's reptile and Water life story,blog.naver.com/seo8810603,20260323
4,4,"숙명여대 편입, <b>인공지능</b>공학부 합격까지 인서울 도전기",https://blog.naver.com/spoly001/224114522439,최근 IT와 AI 분야의 인재 양성에 주력하며 <b>인공지능</b>공학부를 신설해 ...,TV조선캠퍼스평생교육원 공식 블로그,blog.naver.com/spoly001,20251218
5,5,엘지 LG 통돌이 세탁기 추천 용량 17kg <b>인공지능</b> T17WX3,https://blog.naver.com/reser45/224246855986,기술의 발전은 여기서 그치지 않고 <b>인공지능</b> AI과 결합되었습니다. LG...,무스미엘,blog.naver.com/reser45,20260409
6,6,<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI,https://blog.naver.com/alley1980/224229641240,<b>인공지능</b> 교육 AI교육 키트 언플러그드 코딩 주미AI 어느덧 따스한 바...,고고씨네 소소한 일상,blog.naver.com/alley1980,20260325
7,7,[연수기록] <b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전달연수,https://blog.naver.com/dndus3356/224196778376,<b>인공지능</b> 맞춤형 교수학습 플랫폼(AIEP) 전남 - 아이모두 학교 담당...,우연샘의 꿈꾸는 교실,blog.naver.com/dndus3356,20260226
8,8,<b>인공지능</b> 자격증 취득방법 총정리,https://blog.naver.com/wwevoszmffjq/224063279444,<b>인공지능</b> 자격증 취득방법 총정리 그래픽 디자인을 전공하고 5년 동안 근...,왜 안 가인요?,blog.naver.com/wwevoszmffjq,20251103
9,9,"<b>인공지능</b>(AI) 시대, 앞으로 일자리는 어떻게 변할까요?",https://blog.naver.com/molab_suda/224242653040,- ｢APEC 미래 일자리 포럼: <b>인공지능</b>(AI)와 인구구조 변화｣ 개...,고용노동부 공식 블로그,blog.naver.com/molab_suda,20260406
10,10,경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기,https://blog.naver.com/xavisnet/224220577252,"경기 용인 냉동 창고 시설 <b>인공지능</b> CCTV 설치 후기 안녕하세요, 자...",XAVISnet,blog.naver.com/xavisnet,20260318
11,11,"생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교",https://blog.naver.com/teamlinchpin/224177479277,"생성형 <b>인공지능</b> 뜻, 챗지피티·제미나이·클라우드 모델 비교 요즘 뉴스,...","온라인마케팅, 린치핀기획",blog.naver.com/teamlinchpin,20260209
12,12,"AI학원, <b>인공지능</b> 전문가로 성장하는 가장 빠른 방법",https://blog.naver.com/himediacokr/224231103099,최근 AI 대전환이라 느껴질 만큼 우리 주변의 모든 산업이 <b>인공지능</b>을 ...,하이미디어 아카데미 공식블로그,blog.naver.com/himediacokr,20260327
13,13,<b>인공지능</b>전문가 자격증 취득방법 총정리,https://blog.naver.com/gustlr00/224076037551,<b>인공지능</b>전문가 자격증 취득방법 총정리 요즘 AI 관련 뉴스가 하루가 다...,〃다시 만나는 그날 까지 〃,blog.naver.com/gustlr00,20251114
14,14,"학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자)",https://blog.naver.com/jje423/224228420448,"학점은행제 <b>인공지능</b>, 학위 따고 재취업 성공(비전공자) 안녕하세요! 4...",욕심많은 별들맘 이야기,blog.naver.com/jje423,20260325
15,15,직장인 Ai 활용 능력 기르는 <b>인공지능</b> 학사학위,https://blog.naver.com/seo8810603/224224382865,과정으로 <b>인공지능</b> 공학으로 4년제 학사학위를 취득했어요. 온라인으로 학...,Seo's reptile and Water life story,blog.naver.com/seo8810603,20260321
16,16,몰트북 충격 읽어보니 AI 시대 얼마나 바뀔까 <b>인공지능</b> 책 추천,https://blog.naver.com/limhyunae/224248225786,몰트북 충격 읽어보니 AI 시대 얼마나 바뀔까 <b>인공지능</b> 책 추천 요즘 ...,달달한 그녀의 일상,blog.naver.com/limhyunae,20260410
17,17,학점은행제 <b>인공지능</b> 온라인으로 학위 취득했어요,https://blog.naver.com/reebbang/224181846192,저는 비전공자로 직장 생활을 하다가 미래를 위해 학점은행제 <b>인공지능</b> 전...,30's Mood,blog.naver.com/reebbang,20260213
18,18,최소한의 수학』 <b>인공지능</b>을 이해하는 가장 현실적인 방법,https://blog.naver.com/sandhya/224206770826,AI가 쉬워지는 최소한의 수학 이동준2026지상의책(갈매나무) 사람들은 <b>인공지...,밀크티 책세상,blog.naver.com/sandhya,20260306
19,19,"NVIDIA GTC 2026에서 본 <b>인공지능</b> 반도체의 미래! GPU, ...",https://blog.naver.com/nststory2014/224251065664,"<b>인공지능</b> 기술은 단순한 알고리즘 경쟁을 넘어, 실제 구현과 운영을 포함...",국가과학기술연구회,blog.naver.com/nststory2014,20260414